In [1]:
import sys

print(sys.executable)

c:\Users\majom\OneDrive\Desktop\Python Libraries\Numpy\venv\Scripts\python.exe


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
# 2D Array
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([1,2,3])

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.random.rand(5)

array([0.64910235, 0.74001501, 0.83293684, 0.41332006, 0.24011533])

In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


## Mathematical Operations

In [ ]:
arr = np.array([1,2,3])
arr + 2

array([0, 1, 2])

In [17]:
arr - 1

array([0, 1, 2])

In [18]:
arr * 2

array([2, 4, 6])

In [19]:
arr / 2

array([0.5, 1. , 1.5])

## Useful Functions

In [20]:
arr = np.array([10,20,30])

In [21]:
arr.max()

np.int64(30)

In [22]:
arr.min()

np.int64(10)

In [23]:
arr.sum()

np.int64(60)

In [24]:
arr.mean()

np.float64(20.0)

## Indexing

In [25]:
arr = np.array([10, 20, 30, 40])

In [26]:
print(arr[0])

10


In [27]:
print(arr[2])

30


In [28]:
print(arr[-1])

40


In [29]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[1,1])

5


## Slicing

In [30]:
arr = np.array([10,20,30,40,50,60])

In [31]:
print(arr[1:4])

[20 30 40]


In [32]:
print(arr[:3])

[10 20 30]


In [33]:
print(arr[3:])

[40 50 60]


In [34]:
print(arr[::2])

[10 30 50]


In [35]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [36]:
print(arr[0])

[1 2 3]


In [37]:
print(arr[:,1])

[2 5 8]


## Reshaping

In [38]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## Broadcasting

In [ ]:
a = np.array([1,2,3])

b = np.array([10,20,30])

print(a + b)

[11 22 33]


In [40]:
arr = np.array([
    [1,2],
    [3,4]
])

print(arr + 10)

[[11 12]
 [13 14]]


## Boolean Masking

In [41]:
marks = np.array([35, 80, 55, 20, 90])
print(marks > 50)

[False  True  True False  True]


In [42]:
print(marks[marks > 50])

[80 55 90]


In [43]:
ages = np.array([12, 18, 25, 16, 30])
adults = ages >= 18

print(adults)

[False  True  True False  True]


In [44]:
print(ages[adults])

[18 25 30]


In [45]:
numbers = np.array([1,2,3,4,5,6,7,8])

print(numbers[numbers % 2 == 0])

[2 4 6 8]


## Fancy Indexing

In [46]:
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]


In [47]:
names = np.array(["Ali","Sara","John","Emma"])
print(names[[1,3]])

['Sara' 'Emma']


## Aggregation Function

In [48]:
marks = np.array([80, 90, 70, 60, 100])

In [49]:
print(marks.sum())

400


In [50]:
print(marks.mean())

80.0


In [51]:
print(marks.max())

100


In [52]:
print(marks.min())

60


In [53]:
print(marks.std())

14.142135623730951


In [54]:
print(marks.var())

200.0


In [58]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

In [59]:
print(arr.sum())

210


In [60]:
print(arr.sum(axis=0))

[50 70 90]


In [61]:
print(arr.sum(axis=1))

[ 60 150]


## Vectorization

In [65]:
# Without
numbers = np.array([1,2,3,4,5])
result = []

for i in numbers:
    result.append(i * 2)

print(result)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]


In [66]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [67]:
salary = np.array([25000,30000,35000])

salary + 5000

array([30000, 35000, 40000])

In [68]:
a = np.array([1,2,3])

b = np.array([10,20,30])

print(a + b)

[11 22 33]


## Flattening

In [ ]:
# Without
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [70]:
flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


In [72]:
arr = np.array([
    [1,2],
    [3,4]
])

flat = arr.flatten()
print(flat)

[1 2 3 4]


In [73]:
arr.ravel()

array([1, 2, 3, 4])

## Transpose

In [74]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [75]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [76]:
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]
